### PR TITLE
Bring in development + suggestions

### PR DESCRIPTION
**Pull request by cubap**
I've got a TPEN class now and a pattern for the Classes that may be helpful. I've made this a PR, but I'll keep updating the Project.mjs. We can talk about bringing in what it offers later.

### CODE REVIEW

**Comment by cubap** [comment]
@git-voo take a look at this change. Do you want me to refactor your contribution a little as well?

**Comment by cubap** [comment]
image

**Comment by cubap** [comment]
@thehabes @git-voo Where is this at? can it be pulled into the `manage-collaborators` branch? I'm nervous about testing it all out without this included. I suppose it can go separate and be repointed, but it wasn't written like that.

**Comment by thehabes** [comment]
@cubap I didn't test it or review it yet, but if you want it / need it in `manage-collaborators` you can take it forward esp. if it is a blocker.

**Pull request merged**
